---
- name: Configure host to be ready to run George tests
  hosts: all
  vars:
    base_dir: "{{ ansible_user_dir }}/src/opendev.org"
    gate_dest_dir: "{{ base_dir }}/openstack"
    devstack_dir: "{{ base_dir }}/openstack/devstack"
    project_dir: "{{ gate_dest_dir }}/networking-ovn"
  tasks:
    # This is taken from Neutron setup_logging role
    - name: Ensure logdir exists
      become: yes
      vars:
        logdir: /opt/stack/logs
      file:
        path: "{{ logdir }}"
        state: directory
        owner: stack
        group: "{{ ansible_user }}"
        mode: 0775
    # This is taken from configure_functional_tests role
    - name: configure database
      shell:
        cmd: |
          set -e
          set -x
          GATE_STACK_USER={{ ansible_user }}
          IS_GATE=True

          PROJECT_PATH={{ project_dir }}
          DEVSTACK_PATH={{ devstack_dir }}

          source $DEVSTACK_PATH/functions
          $PROJECT_PATH/tools/configure_for_func_testing.sh $DEVSTACK_PATH -i
        executable: /bin/bash
    - name: "WORKAROUND: add atomic ubuntu repositories"
      shell:
        cmd: |
          apt update
          apt -y  install software-properties-common
          add-apt-repository -y ppa:projectatomic/ppa
          apt update
        executable: /bin/bash
      when: ansible_distribution == 'Ubuntu'
      become: yes

    - name: install podman and buildah
      package:
        name:
          - podman
          - runc
          - buildah
          - containernetworking-plugins
          - containers-common
          - containers-golang
          - containers-image
        state: latest
      become: yes

    - name: insert openvswitch and vport-geneve modules
      modprobe:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - openvswitch
        - vport-geneve

    - name: "WORKAROUND: Set cni net.d writable for everyone"
      file:
        path: /etc/cni/net.d/
        mode: '0777'
      become: yes

    - name: build container images
      shell:
        cmd: |
          set -e
          set -x
          {{ project_dir }}/networking_ovn/tests/contrib/george/build_container_images.sh
        executable: /bin/bash
